In [ ]:

#  q1.  Create a 5 × 5 NumPy matrix containing numbers from 1 to 25 and 
# print: 
# ○ The first row 
# ○ The last column 
# ○ The diagonal elements

matrix = np.arange(1, 26).reshape(5, 5)

print("Matrix:")
print(matrix)

print("\nFirst row:")
print(matrix[0])

print("\nLast column:")
print(matrix[:, -1])

print("\nDiagonal elements:")
print(np.diag(matrix))

Matrix:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

First row:
[1 2 3 4 5]

Last column:
[ 5 10 15 20 25]

Diagonal elements:
[ 1  7 13 19 25]


In [ ]:
# q2. Create two 3 × 3 matrices and perform matrix addition, subtraction, and matrix multiplication.



A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])


print("Addition of A and B:")
print(A + B)


print("\nSubtraction of A and B:")
print(A - B)


print("\nMatrix multiplication of A and B:")
print(A @ B)      

Addition of A and B:
[[10 10 10]
 [10 10 10]
 [10 10 10]]

Subtraction of A and B:
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]

Matrix multiplication of A and B:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [3]:
# q3. Create a NumPy array of numbers from 1 to 100 and print all numbers divisible by 3 using Boolean indexing. arr = np.arange(1, 101)

arr = np.arange(1, 101)
div_by_3 = arr[arr % 3 == 0]
print("Numbers divisible by 3:")
print(div_by_3)


Numbers divisible by 3:
[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72
 75 78 81 84 87 90 93 96 99]


In [4]:
# q4. Create a 4 × 4 matrix and replace all even numbers with 0.

matrix = np.arange(1, 17).reshape(4, 4)
matrix[matrix % 2 == 0] = 0
print(matrix)

[[ 1  0  3  0]
 [ 5  0  7  0]
 [ 9  0 11  0]
 [13  0 15  0]]


In [6]:
# q5.  Create a 5 × 5 matrix of random integers and find: 
# ○ Maximum value 
# ○ Minimum value 
# ○ Mean 
# ○ Median

matrix = np.random.randint(1, 101, size=(5, 5))
print("Matrix:")
print(matrix)
print("\nMaximum value:", np.max(matrix))
print("Minimum value:", np.min(matrix))
print("Mean:", np.mean(matrix))
print("Median:", np.median(matrix))

Matrix:
[[ 49  71  59  83  23]
 [ 81  91  88  46  65]
 [  5  13   6  55  83]
 [ 44  62  57  54  69]
 [ 97 100  92  48  14]]

Maximum value: 100
Minimum value: 5
Mean: 58.2
Median: 59.0


In [7]:
# q6.  Create a NumPy array containing 20 random numbers and sort it in ascending and descending order.




arr = np.random.randint(1, 101, size=20)


print("Original array:")
print(arr)

ascending = np.sort(arr)
print("\nAscending order:")
print(ascending)


descending = np.sort(arr)[::-1]
print("\nDescending order:")
print(descending)

Original array:
[91 43 37 35 38 52 76 22 98  1 30  4 97 90 63 98  8 74 20 41]

Ascending order:
[ 1  4  8 20 22 30 35 37 38 41 43 52 63 74 76 90 91 97 98 98]

Descending order:
[98 98 97 91 90 76 74 63 52 43 41 38 37 35 30 22 20  8  4  1]


In [8]:
# q7. 

matrix = np.arange(1, 37).reshape(6, 6)


print("Matrix:")
print(matrix)


print("\nMain diagonal:")
print(np.diag(matrix))


print("\nUpper triangular part:")
print(np.triu(matrix))

print("\nLower triangular part:")
print(np.tril(matrix))

Matrix:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]

Main diagonal:
[ 1  8 15 22 29 36]

Upper triangular part:
[[ 1  2  3  4  5  6]
 [ 0  8  9 10 11 12]
 [ 0  0 15 16 17 18]
 [ 0  0  0 22 23 24]
 [ 0  0  0  0 29 30]
 [ 0  0  0  0  0 36]]

Lower triangular part:
[[ 1  0  0  0  0  0]
 [ 7  8  0  0  0  0]
 [13 14 15  0  0  0]
 [19 20 21 22  0  0]
 [25 26 27 28 29  0]
 [31 32 33 34 35 36]]


In [9]:
# q8. 


arr = np.arange(1, 21)


matrix_4x5 = arr.reshape(4, 5)
print("4 × 5 matrix:")
print(matrix_4x5)

matrix_2x10 = arr.reshape(2, 10)
print("\n2 × 10 matrix:")
print(matrix_2x10)

matrix_5x4 = arr.reshape(5, 4)
print("\n5 × 4 matrix:")
print(matrix_5x4)

4 × 5 matrix:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

2 × 10 matrix:
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]

5 × 4 matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [10]:
# q9. 

matrix = np.arange(1, 26).reshape(5, 5)


print("Matrix:")
print(matrix)

row_sum = np.sum(matrix, axis=1)
print("\nSum of each row:")
print(row_sum)

col_sum = np.sum(matrix, axis=0)
print("\nSum of each column:")
print(col_sum)

Matrix:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Sum of each row:
[ 15  40  65  90 115]

Sum of each column:
[55 60 65 70 75]


In [11]:
# q10. 

arr1 = np.array([1, 2, 3, 4, 5, 6, 7])
arr2 = np.array([4, 5, 6, 7, 8, 9, 10])

common = np.intersect1d(arr1, arr2)

print("Array 1:", arr1)
print("Array 2:", arr2)
print("Common elements:", common)

Array 1: [1 2 3 4 5 6 7]
Array 2: [ 4  5  6  7  8  9 10]
Common elements: [4 5 6 7]


In [12]:
# q11. 

matrix = np.random.randint(1, 101, size=(5, 5))


print("Matrix:")
print(matrix)

largest = np.max(matrix)
print("\nLargest element:", largest)

position = np.unravel_index(np.argmax(matrix), matrix.shape)
print("Position (row, column):", position)

Matrix:
[[81 12 97 75  8]
 [36 69 94 86 26]
 [20 19  2 91 58]
 [40 72 24 38 60]
 [99 27 56 13 67]]

Largest element: 99
Position (row, column): (np.int64(4), np.int64(0))
